fix horizon
Apply patch 06c81a4a071270f4ba9ffabf218f0b187e141e22 from
openstack/manila-ui with commit message:

   Fix get_disabled_quotas

  Disabled quotas should be treated as a set, not as a list, or else
  instead of action buttons we'll get a traceback:

  File "/manila-ui/manila_ui/dashboards/project/shares/__init__.py",
      line 129, in get_disabled_quotas
      disabled_quotas.extend(_get_manila_disabled_quotas(request))
  AttributeError: 'set' object has no attribute 'extend'

  Closes-Bug: #1611368

Change-Id: I262c0dc15073c89b8c4df4b57bd147384ec4cc9f